#[derive(PartialOrd, PartialEq, Debug, Copy, Clone)]
pub enum SyntaxKind {
    TombStone,
    Error(&'static str),
    GroupingExpr,
    BinaryExpr,
    UnaryExpr,
    PrimitiveLiteralExpr,
    ObjectLiteralExpr,
    ObjectPropertyExpr,
    ObjectPropertyRVal,
    VariableExpr,
    FunctionCallExpr,
    VariableDeclarationStmt,
    VariableAssignmentStmt,
    VariableRval,
    StmtListStmt,
    ExprStmt,
    IfStmt,
    WhileStmt,
    FunctionDeclarationStmt,
    ReturnStmt,
}
